version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password      
      - POSTGRES_DB=vibbra
    ports:
      - "5432:5432"
  api:
    container_name: backend
    image: node:16
    working_dir: /usr/src/vibbra
    command: bash -c "npm install && npm run start:prod"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=vibbra
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PORT=3000
    volumes:
      - ./dist/:/usr/src/vibbra/dist/
      - ./package.json:/usr/src/vibbra/package.json
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    links:
      - "postgres"